### ISSUE TITLE
Almost all tests are gone from rulecontrol.xml

### ISSUE THREAD

**Issue by uythoang** [RESOStandards/RESO-WebAPI-Client-dotNet#12]
### Description

All the tests, except for ServiceImpl_SystemQueryOptionFilter_Year, have been removed from rulecontrol.xml: https://github.com/RESOStandards/RESO-WebAPI-Client-dotNet/commit/652c3d3795e9be9f968c6c6a5b14a1f6db3699fe#diff-b688d6b86477bd6febe9ff21f2971995

**Comment by sschuessler** [comment]
There was an error on the upload.  That test was being worked on.  I apologize.  Attached is the rulecontrol.xml file.  Replace it here  ./RESOReference/bin/Debug/config/rulecontrol.xml

[rulecontrol.zip](https://github.com/RESOStandards/RESO-WebAPI-Client-dotNet/files/3039349/rulecontrol.zip)

**Comment by uythoang** [comment]
Thanks
